kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "astro.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "astro.name" . }}
    helm.sh/chart: {{ include "astro.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  OWNER: {{ .Values.owner }}
  DRY_RUN: {{ .Values.dryRun | quote }}
{{- if .Values.custom_config.enabled }}
  {{- if .Values.custom_config.configMapOverride }}
    {{- $paths := list }}
    {{- range .Values.custom_config.configMapOverride.rulesetFiles }}
      {{- $paths = printf "/etc/config/%s" . | append $paths }}
    {{- end }}
  DEFINITIONS_PATH: {{ join ";" $paths }}
  {{- else }}
  DEFINITIONS_PATH: /etc/config/config.yml
  {{- end }}
{{- else }}
  DEFINITIONS_PATH: {{ .Values.definitionsPath }}
{{- end }}
